# Generated by Django 3.0.4 on 2020-03-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('dname', models.CharField(max_length=15)),
                ('d_no', models.IntegerField(primary_key=True, serialize=True)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('e_id', models.IntegerField(primary_key=True, serialize=False)),
                ('salary', models.IntegerField()),
                ('d_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='menu',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20)),
                ('veg', models.CharField(max_length=2)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tabss',
            fields=[
                ('t_no', models.IntegerField(primary_key=True, serialize=False)),
                ('cap', models.IntegerField()),
                ('avl', models.CharField(max_length=1)),
            ],
        ),
    ]
