# Generated by Django 3.0.4 on 2020-03-25 13:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('b_no', models.IntegerField(primary_key=True, serialize=False)),
                ('amt', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('t_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.tabss')),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField()),
                ('name', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('b_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.bill')),
            ],
        ),
    ]
