# Generated by Django 3.0.4 on 2020-04-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_bill_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='e_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
