# Generated by Django 3.0.4 on 2020-04-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_auto_20200428_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='b_no',
            new_name='b_id',
        ),
        migrations.AlterField(
            model_name='tabss',
            name='t_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
