# Generated by Django 3.0.4 on 2020-05-02 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_auto_20200501_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rest.menu'),
        ),
    ]
