# Generated by Django 3.0.4 on 2020-05-02 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_auto_20200502_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='cost',
        ),
    ]
