# Generated by Django 3.0.4 on 2020-05-02 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0008_remove_orders_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='sl_no',
        ),
    ]
