# Generated by Django 3.0.4 on 2020-05-04 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0009_remove_orders_sl_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='b_no',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='name',
        ),
        migrations.DeleteModel(
            name='bill',
        ),
        migrations.DeleteModel(
            name='menu',
        ),
        migrations.DeleteModel(
            name='orders',
        ),
    ]
