# Generated by Django 3.0.4 on 2020-05-11 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0010_auto_20200505_0151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tabss',
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['d_no']},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['d_no']},
        ),
        migrations.AlterModelTable(
            name='department',
            table='department',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
