# Generated by Django 3.0.4 on 2020-06-15 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dept',
            fields=[
                ('dname', models.CharField(max_length=15)),
                ('d_no', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dept',
                'ordering': ['d_no'],
            },
        ),
        migrations.CreateModel(
            name='employ',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('e_id', models.AutoField(primary_key=True, serialize=False)),
                ('salary', models.IntegerField()),
                ('contact_no', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=30)),
                ('d_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rests.dept')),
            ],
            options={
                'db_table': 'employ',
                'ordering': ['d_no'],
            },
        ),
    ]
