# Generated by Django 3.0.4 on 2020-05-14 23:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('amt', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='menu',
            fields=[
                ('item_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('veg', models.CharField(max_length=2)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('b_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.bill')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='order.menu')),
            ],
        ),
    ]
